### ISSUE TITLE
Proximity radio

### ISSUE THREAD

**Issue by jmanzo** [alexpechkarev/google-maps#24]
Hi, I'm working on an app that should filter the nearby items within a radius of 20km. I have stored in db lat and lng, how could I implement it in your plugin? I searched but I do not understand and I need your help.

Thank you for your awesome contributions!

**Comment by Rapzac** [comment]
As far im aware, this module got some issues, when im trying to call googles api, my return is a string.. 

the solution is:

`\GoogleMaps::load('geocoding')->setParam (['address' =>'santa cruz','components' => [
'administrative_area'  => 'TX',
'country'              => 'US',
]])->setEndpoint('json')->get();

$address = trim(preg_replace('/\s+/', ' ', $address));
$address = json_decode($address);
`

now i get my result in json, i can work with..

**Comment by alexpechkarev** [comment]
Hi @Rapzac ,

Thank you for your response.

If you would access following URL:
https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&key=YOUR_API_KEY

 (add your API key at the end) you will get JSON response, this is because the responding server include following header: `content-type:application/json; charset=UTF-8` that makes your browser to interpret the response as JSON.

The response you obtained from this package as per your code is string containing JSON object, that you have to convert into PHP variable, which you did.

```
 $r = \GoogleMaps::load('geocoding')->setParam (['address' =>'santa cruz','components' => [
'administrative_area' => 'TX',
'country' => 'US',
]])->setEndpoint('json')->get();
    
    dd( json_decode($r,true)  ); // will return an array

array:2 [▼
  "results" => array:1 [▼
    0 => array:6 [▼
      "address_components" => array:2 [▼
        0 => array:3 [▼
          "long_name" => "Texas"
          "short_name" => "TX"
          "types" => array:4 [▶]
        ]
        1 => array:3 [▼
          "long_name" => "United States"
          "short_name" => "US"
          "types" => array:2 [▼
            0 => "country"
            1 => "political"
          ]
        ]
      ]
      "formatted_address" => "Texas, USA"
      "geometry" => array:4 [▼
        "bounds" => array:2 [▶]
        "location" => array:2 [▶]
        "location_type" => "APPROXIMATE"
        "viewport" => array:2 [▼
          "northeast" => array:2 [▶]
          "southwest" => array:2 [▶]
        ]
      ]
      "partial_match" => true
      "place_id" => "ChIJSTKCCzZwQIYRPN4IGI8c6xY"
      "types" => array:4 [▶]
    ]
  ]
  "status" => "OK"
]

```
